### ISSUE TITLE
danmnets could not work after the upgrade of DANM from 3.x to 4.x

### ISSUE THREAD

**Issue by clivez** [nokia/danm#164]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 bug
> feature

**What happened**:
There is a "Spec.Validation" field in danmnet in version 3.x, but no such field in DANM 4.x.
And decoder.DisallowUnknownFields() is set inside webhook, so when operating these danmnets created by DANM 3.x, the webhook will alwasy return an error, and the operation will fail.

**What you expected to happen**:
danmnets created by old version DANM can work after the upgrade of DANM

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by clivez** [comment]
https://github.com/nokia/danm/blob/v4.0.0/pkg/admit/netadmit.go#L78

**Comment by clivez** [comment]
And there is also another case, not caused by upgrade.
In one of our setups, k8s adds "managedFields" into danmnets, and this will also cause problem because webhook does not allow unknown fields.

**Comment by Levovar** [comment]
we have never stated you can simply upgrade from 3.X to 4.X architecture as is
definitely recreate your networks after upgrade

regarding managedFields: K8s documentation states that this is stored in the **annotation** field of the object, which is decoded based on the upstream K8s schema
it should not result in decode errors - unless the managedFields was manually added to the body of the CRD

logs pls!

**Comment by Levovar** [comment]
any news on this one?

**Comment by Levovar** [comment]
@clivez I will close if there are no further logs related to this issue
